@startuml
state isWriteContext <<choice>>
state isWriteQuery <<choice>>
state isReplicaConsistent <<choice>>
state canUseReplica <<choice>>


NoConnection   ---> isWriteContext : **Initial query**\n\nis write context?
isWriteContext ---> MainConnection   : Yes

isWriteContext --> isWriteQuery : No\n\nis write query?
isWriteQuery ---> MainConnection : Yes
isWriteQuery ---> canUseReplica: No\n\ncan use replica?


canUseReplica ---> isReplicaConsistent: Yes\n\nis replica consistent?
canUseReplica ---> CommitedMain: No


isReplicaConsistent ---> ReplicaConnection : Yes
isReplicaConsistent ---> CommitedMain : No
CommitedMain ---> isWriteContext : **Next query**\n\nis write context?

MainConnection ---> MainConnection : **Next query**
ReplicaConnection ---> isWriteContext : **Next query**\n\nis write context?

NoConnection ---> ClosedConnection
MainConnection ---> ClosedConnection
ReplicaConnection ---> ClosedConnection

@enduml
