@startuml

@startuml

class DualConnection

interface DatabaseCall{
  <T> T call( SqlCall<T> call, RouteDecision routeDecision)
}

DualConnection *-- DatabaseCall
DualConnection --> DatabaseCall::call : db operation


@enduml


@enduml
