name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release? Major/Minor/Patch/None'
        required : true
        default: 'None'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-${{ hashFiles('gradle') }}
    - name: Build
      run: ./gradlew build
    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: build/reports/tests
    - name: Release
      if: github.event.inputs.release != null && github.event.inputs.release != 'None'
      env:
        atlassian_private_username: ${{ secrets.ARTIFACTORY_USERNAME }}
        atlassian_private_password: ${{ secrets.ARTIFACTORY_API_KEY }}
      run: |
        ./gradlew markNextVersion -Prelease.incrementer=increment${{ github.event.inputs.release }} -Prelease.localOnly
        ./gradlew release -Prelease.customUsername=${{ secrets.REPOSITORY_ACCESS_TOKEN }}
        ./gradlew publish
